development:
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

  google_client_id: "558803244328-erveo1gb8bth5539s4gqrb8jfas57o6j.apps.googleusercontent.com"
  google_client_secret: "6b4SeFNd5ELeTVv_X7QVyAzJ"

  facebook_client_id: "2504964336281105"
  facebook_client_secret: "7bcd1d6ce73cbd2bf683ef6d6d6790e4"

production:
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>